### ISSUE TITLE
支持域名查询

### ISSUE THREAD

**Issue by qinghuas** [helloxz/IPinfo#1]
应当支持通过域名查询，以下代码可供参考

function GET_DOMAIN($DATA){
		$GET_URL_DATA = parse_url($DATA);
		$DOMAIN = trim($GET_URL_DATA['host'] ? $GET_URL_DATA['host'] : array_shift(explode('/', $GET_URL_DATA['path'], 2)));
		return $DOMAIN;
	}

if (!preg_match('/^(?:(?:2[0-4][0-9]\.)|(?:25[0-5]\.)|(?:1[0-9][0-9]\.)|(?:[1-9][0-9]\.)|(?:[0-9]\.)){3}(?:(?:2[0-5][0-5])|(?:25[0-5])|(?:1[0-9][0-9])|(?:[1-9][0-9])|(?:[0-9]))$/', $DATA)) {
			$IP_DATA = gethostbyname(GET_DOMAIN($DATA));

**Comment by helloxz** [comment]
谢谢，正在改进中。

**Comment by helloxz** [comment]
通过域名查询已经完成，再次表示感谢。
